### ISSUE TITLE
Warning: parse cpp configuration error!

### ISSUE THREAD

**Issue by TuRan-sino** [github0null/eide#98]
<b>解析C/C++配置的时候发生错误</b><br>

标题是VsCode打开时给我报的错误, 看样子应该是C/C++解析不了本插件提供的参数<br>具体表现就是
1.  所有的函数和头文件转不到定义, 显示 `no definition founded`
2.  C/C++提供的`PROBLEMS`一直显示 "无法打开源文件 ......."
3. `output` 里面的 `eide-cpptools-log`显示空白, 没有任何内容
4. 每次删除插件重新安装之后不关闭VSCODE的前提下继续使用插件没有这个问题.  **但是, 在重启vscode之后这个问题又会重新回来**
5. 删除插件第一次安装时现`eide-cpptools-log`是有内容的, 显示内容如下
```
[init] register CustomConfigurationProvider done !

[folder] provideFolderBrowseConfiguration for 'd:\Work\Project\Graduation\KEIL'
browsePath: []
compilerPath: null
compilerArgs: null

[source] provideConfigurations
- uri:
    $mid: 1
    fsPath: d:\Work\Project\Graduation\USER\main.c
    _sep: 1
    path: /D:/Work/Project/Graduation/USER/main.c
    scheme: file
  configuration:
    standard: c99
    includePath:
      - d:/Work/Project/Graduation/CORE
      - d:/Work/Project/Graduation/USER
      - d:/Work/Project/Graduation/FWLIB/inc
      - d:/Work/Project/Graduation/HARDWARE
      - d:/Work/Project/Graduation/SYSTEM
      - d:/Work/Project/Graduation/KEIL/.eide/deps
      - D:/Keil_v5/ARM/ARMCC/include
      - D:/Keil_v5/ARM/ARMCC/include/rw
    defines:
      - __VSCODE_CPPTOOL
      - STM32F10X_HD
      - USE_STDPERIPH_DRIVER
    forcedInclude:
      - c:\Users\13275\.vscode\extensions\cl.eide-2.16.6\bin\include\internal_headers\armcc_intr.h
    compilerPath: null
    compilerArgs: null

[folder] provideFolderBrowseConfiguration for 'd:\Work\Project\Graduation\KEIL'
browsePath:
  - d:/Work/Project/Graduation/USER/*
  - d:/Work/Project/Graduation/SYSTEM/*
  - d:/Work/Project/Graduation/HARDWARE/*
  - d:/Work/Project/Graduation/FWLIB/src/*
  - d:/Work/Project/Graduation/CORE/*
compilerPath: null
compilerArgs: null

[source] provideConfigurations
- uri:
    $mid: 1
    fsPath: d:\Work\Project\Graduation\USER\main.c
    _sep: 1
    path: /D:/Work/Project/Graduation/USER/main.c
    scheme: file
  configuration:
    standard: c99
    includePath:
      - d:/Work/Project/Graduation/CORE
      - d:/Work/Project/Graduation/USER
      - d:/Work/Project/Graduation/FWLIB/inc
      - d:/Work/Project/Graduation/HARDWARE
      - d:/Work/Project/Graduation/SYSTEM
      - d:/Work/Project/Graduation/KEIL/.eide/deps
      - D:/Keil_v5/ARM/ARMCC/include
      - D:/Keil_v5/ARM/ARMCC/include/rw
    defines:
      - __VSCODE_CPPTOOL
      - STM32F10X_HD
      - USE_STDPERIPH_DRIVER
    forcedInclude:
      - c:\Users\13275\.vscode\extensions\cl.eide-2.16.6\bin\include\internal_headers\armcc_intr.h
    compilerPath: null
    compilerArgs: null
```
6. `c_cpp_propertise.json`显示内容如下<br>
![image](https://user-images.githubusercontent.com/51948125/151660438-82de77e8-654a-4b74-9ca4-d698bce28ba0.png)
7. 重启之后vscode报错如下<br>
```
Warning: parse cpp configuration error!
```
---
之前我浏览过你在Forum里面的回答, 我按照你讲的方式卸载过插件, 似乎没有用<br>在这之后我怀疑可能是你之前写的插件`keil assistant`出了问题, 所以我把`c_cpp_properties.json`里面的内容给全部删除了, 重新import了一个工程, 并且删除了`keil assistant`发现问题还是没有解决
